version: '3'
services:
  nginx:
    ports:
      - "3000:80"
  campus-delivery:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/server
      - /server/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=sanjeev
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=sanjeev
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

