# Generated by Django 4.2 on 2025-06-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        default="https://placehold.co/600x400/000000/FFFFFF?text=Product",
                        max_length=2000,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("digital", models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
